apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-server
  labels:
    service: {{ .Chart.Name }}-server
spec:
  replicas: 3
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-server
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}-server
    spec:
      containers:
      - name: web-server
{{ tuple "werf-web" . | werf_container_image | indent 8 }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
{{ tuple "werf-web" . | werf_container_env | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server
spec:
  clusterIP: None
  selector:
    service: {{ .Chart.Name }}-server
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
